# Generated by Django 2.1.4 on 2019-01-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_collector', '0002_auto_20181225_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seismicrecord',
            name='amplitude',
            field=models.FloatField(default=5),
        ),
    ]
